import { v4 as uuidv4 } from 'uuid';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link';
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <Link href="/" passHref>Home</Link>
          <Link href="/events" passHref>Events</Link>
          <Link href="/about" passHref>About us</Link>
        </nav>
      </header>
      <main>
        {data.map((event) => (
          <Link key={uuidv4()} href={`/events/${event.id}`} passHref>
            <div>
              <Image src={event.image} alt={`${event.id} event`} width={200} height={200} priority />
              <h2>{event.title}</h2>
              <p>{event.description}</p>
            </div>
          </Link>
        ))}
      </main>
      <footer>
        <p>All Right Reserved 2023 Chelobotix</p>
      </footer>
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json')
  return {
    props: {
      data: events_categories,
    }
  }
}


