import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about">About us</a>
        </nav>
      </header>
      <main>
        <a href="">
          <div>
            <h2>Events in London</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Deserunt dignissimos obcaecati saepe aperiam tempore omnis
              dolores maiores facere aliquid nesciunt.</p>
          </div>
        </a>
        <a href="">
          <div>
            <h2>Events in San Francisco</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Deserunt dignissimos obcaecati saepe aperiam tempore omnis
              dolores maiores facere aliquid nesciunt.</p>
          </div>
        </a>
        <a href="">
          <div>
            <h2>Events in Rio de Janeiro</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Deserunt dignissimos obcaecati saepe aperiam tempore omnis
              dolores maiores facere aliquid nesciunt.</p>
          </div>
        </a>
      </main>
      <footer>
        <p>All Right Reserved 2023 Chelobotix</p>
      </footer>
    </>
  )
}
